@authHost = {{BASE_URL}}/auth


### GET /auth/me

GET {{authHost}}/me HTTP/1.1
Authorization: {{Security.Auth}}

### GET /auth/refresh

GET {{authHost}}/refresh HTTP/1.1
Cookie: {{Security.Refresh}}

### GET /auth/google

GET {{authHost}}/google HTTP/1.1

### POST /auth/register

POST {{authHost}}/register HTTP/1.1

{
  "address": "Vietnam",
  "email": "azong@gmail.com",
  "firstName": "zong",
  "lastName": "muas",
  "password": "12345678"
}

### POST /auth/login

POST {{authHost}}/login HTTP/1.1

{
  "email": "azong@gmail.com",
  "password": "12345678"
}

### POST /auth/logout

POST {{authHost}}/logout HTTP/1.1
