### 

@authHost = http://localhost:5500/api/auth


### 

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDcyZWVmNi0xMzhhLTQxZjktODNkNS1jZTMwNjU0YzU2NWIiLCJmdWxsTmFtZSI6Ik1pa2UgbXVhcyIsInJvbGUiOiJjbGllbnQiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzU3NzMwMDQ2LCJleHAiOjE3NTc3MzA5NDZ9.dhKQCG5p-meIXcB7XA8Ltny5pWAgKBvYvYda4GtW_w0
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0Mzg1NWY0Ny04YTE1LTQ3ODYtYjM3Zi0yYjA2YTI0MzE4YTMiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc1NzU1NTkxOCwiZXhwIjoxNzU4MTYwNzE4fQ.4RsPnmsuurih7ETgOCZrFwF-V9IUSkxX56nh-oOer2c


### GET /auth/me

GET {{authHost}}/me HTTP/1.1
Authorization: Bearer {{accessToken}}


### GET /auth/refresh

GET {{authHost}}/refresh HTTP/1.1
Cookie: refresh={{refreshToken}}


### GET /auth/google

GET {{authHost}}/google HTTP/1.1


### POST /auth/register

POST {{authHost}}/register HTTP/1.1
Content-Type: application/json

{
  "address": "Vietnam",
  "email": "azong@gmail.com",
  "firstName": "zong",
  "lastName": "muas",
  "password": "12345678"
}


### POST /auth/login

POST {{authHost}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "azong@gmail.com",
  "password": "123456789"
}


### POST /auth/logout

POST {{authHost}}/logout HTTP/1.1
