### 

@cartItemsHost = http://localhost:5500/api/cart-items
@userId = 2c995947-643d-49a5-a233-009a8180ed6e


### GET /api/cart-items/:userId

GET {{cartItemsHost}}/{{userId}} HTTP/1.1


### POST /api/cart-items

POST {{cartItemsHost}} HTTP/1.1
Content-Type: application/json

{
  "productId": "81105e85-60bd-47e1-8547-c7133385f91d",
  "quantity": 10,
  "userId": "{{userId}}"
}
