@categoriesHost = {{BASE_URL}}/categories


### GET /categories

GET {{categoriesHost}} HTTP/1.1

### GET /categories/:id

GET {{categoriesHost}}/{{CATEGORY_ID}} HTTP/1.1

### GET /categories/:id/products

GET {{categoriesHost}}/{{CATEGORY_ID}}/products HTTP/1.1

### POST /categories

POST {{categoriesHost}} HTTP/1.1
Authorization: {{Security.Auth}}

{
  "name": "Cake",
  "description": "Cake desc"
}

### PATCH /categories/:id

PATCH {{categoriesHost}}/{{categoryId}} HTTP/1.1
Authorization: {{Security.Auth}}

{
  "name": "Orange2",
  "description": "A delicious fruit2"
}

### DELETE /categories/:id

DELETE {{categoriesHost}}/{{categoryId}} HTTP/1.1
Authorization: {{Security.Auth}}
