@mediaHost = {{BASE_URL}}/media
@mediaUserApi = {{mediaHost}}/user


### GET /media/user/:userId/avatar

GET {{mediaUserApi}}/{{USER_ID}}/avatar HTTP/1.1
Authorization: {{Security.Auth}}

### GET /media/user/:userId/cover

GET {{mediaUserApi}}/{{USER_ID}}/cover HTTP/1.1
Authorization: {{Security.Auth}}

### GET /media/user/:userId/images

GET {{mediaUserApi}}/{{USER_ID}}/images HTTP/1.1
Authorization: {{Security.Auth}}

### POST /media/user/:userId/avatar

POST {{mediaUserApi}}/{{USER_ID}}/avatar HTTP/1.1
Authorization: {{Security.Auth}}
Content-Type: multipart/form-data

### POST /media/user/:userId/cover

POST {{mediaUserApi}}/{{USER_ID}}/cover HTTP/1.1
Authorization: {{Security.Auth}}
Content-Type: multipart/form-data

### DELETE /media/user/:userId/avatar

DELETE {{mediaUserApi}}/{{USER_ID}}/avatar HTTP/1.1
Authorization: {{Security.Auth}}

### DELETE /media/user/:userId/cover

DELETE {{mediaUserApi}}/{{USER_ID}}/cover HTTP/1.1
Authorization: {{Security.Auth}}
