### 

@mediaHost = http://localhost:5500/media
@mediaUserApi = {{mediaHost}}/user
@userId = 7a4ad4be-32da-488e-86bd-e751706748ad


### GET /media/user/:userId/avatar

GET {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1


### GET /media/user/:userId/cover

GET {{mediaUserApi}}/{{userId}}/cover HTTP/1.1


### GET /media/user/:userId/images

GET {{mediaUserApi}}/{{userId}}/images HTTP/1.1


### POST /media/user/:userId/avatar

POST {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1
Content-Type: multipart/form-data


### POST /media/user/:userId/cover

POST {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
Content-Type: multipart/form-data


### PUT /media/user/:userId/avatar

PUT {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1
Content-Type: multipart/form-data


### PUT /media/user/:userId/cover

PUT {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
Content-Type: multipart/form-data


### DELETE /media/user/:userId/avatar

DELETE {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1


### DELETE /media/user/:userId/cover

DELETE {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
