### 

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMTE3MTBjZS1kNDBiLTRmNTYtOTdjZS1lNTI4MjVjOWYyNTkiLCJmdWxsTmFtZSI6InpvbmcgbXVhcyIsInJvbGUiOiJjbGllbnQiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzU3NzIzOTc4LCJleHAiOjE3NTc3MjQ4Nzh9.hHwtGw6sZbbaMZ7sxwlrV5sSUHFtV0mCrvXSvbJCl1E
@mediaHost = http://localhost:5500/api/media
@mediaUserApi = {{mediaHost}}/user
@userId = c11710ce-d40b-4f56-97ce-e52825c9f259


### GET /media/user/:userId/avatar

GET {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}


### GET /media/user/:userId/cover

GET {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
Authorization: Bearer {{accessToken}}


### GET /media/user/:userId/images

GET {{mediaUserApi}}/{{userId}}/images HTTP/1.1
Authorization: Bearer {{accessToken}}


### POST /media/user/:userId/avatar

POST {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data


### POST /media/user/:userId/cover

POST {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data


### PUT /media/user/:userId/avatar

PUT {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data


### PUT /media/user/:userId/cover

PUT {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data


### DELETE /media/user/:userId/avatar

DELETE {{mediaUserApi}}/{{userId}}/avatar HTTP/1.1
Authorization: Bearer {{accessToken}}


### DELETE /media/user/:userId/cover

DELETE {{mediaUserApi}}/{{userId}}/cover HTTP/1.1
Authorization: Bearer {{accessToken}}
