@productHost = {{BASE_URL}}/products


### GET /products?limit=3&page&sort=asc

GET {{productHost}}
  ?search=lemon
  &page=1
   HTTP/1.1 HTTP/1.1

### GET /products/:id

GET {{productHost}}/{{PRODUCT_ID}} HTTP/1.1

### POST /products

POST {{productHost}} HTTP/1.1
Authorization: {{Security.Auth}}

{
  "description": "A delicious fruit",
  "name": "Orange",
  "price": 100000,
  "rating": 5,
  "stock": 120
}

### POST /products/:id/category

POST {{productHost}}/{{PRODUCT_ID}}/category HTTP/1.1
Authorization: {{Security.Auth}}

{
  "categoryId": "{{CATEGORY_ID}}"
}

### PATCH /products/:id

PATCH {{productHost}}/{{PRODUCT_ID}} HTTP/1.1
Authorization: {{Security.Auth}}

{
  "rating": 4
}

### DELETE /products/:id/category

DELETE {{productHost}}/{{PRODUCT_ID}}/category HTTP/1.1
Authorization: {{Security.Auth}}

### DELETE /products/:id

DELETE {{productHost}}/{{PRODUCT_ID}} HTTP/1.1
Authorization: {{Security.Auth}}
