### 

@userHost = http://localhost:5500/users
@userId = 60d7f703-70c7-4db0-ad86-ba09a0416f10


### GET /users

GET {{userHost}} HTTP/1.1


### GET /user/:id

GET {{userHost}}/{{userId}} HTTP/1.1


### PATCH /users/:id

PATCH {{userHost}}/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "firstName": "test"
}


### POST /users

POST {{userHost}} HTTP/1.1
Content-Type: application/json

{
  "email": "azong5@gmail.com",
  "firstName": "azong6",
  "lastName": "moua2",
  "password": "123456",
  "username": "azonlll"
}


### DELETE /user/:id

DELETE {{userHost}}/{{userId}} HTTP/1.1
