@userHost = {{BASE_URL}}/users


### GET /users

GET {{userHost}} HTTP/1.1
Authorization: {{Security.Auth}}

### GET /users?limit=1&page=1&sort=desc

GET {{userHost}}?limit=2
  &page=1
  &sort=asc HTTP/1.1
Authorization: {{Security.Auth}}

### GET /user/:id

GET {{userHost}}/{{USER_ID}} HTTP/1.1
Authorization: {{Security.Auth}}

### PATCH /users/:id

PATCH {{userHost}}/{{USER_ID}} HTTP/1.1
Authorization: {{Security.Auth}}

{
  "firstName": "aZong",
  "lastName": "hello",
  "password": "123456789"
}

### POST /users -- for admin only

POST {{userHost}} HTTP/1.1
Authorization: {{Security.Auth}}

{
  "address": "Vietnam",
  "email": "azong12@gmail.com",
  "firstName": "zong",
  "lastName": "muas",
  "password": "123456"
}

### DELETE /user/:id

DELETE {{userHost}}/{{USER_ID}} HTTP/1.1
Authorization: {{Security.Auth}}
